# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build all modules
      run: |
        for dir in */; do
          if [ -f "$dir/go.mod" ]; then
            echo "Building $dir"
            cd "$dir"
            go build -v .
            cd ..
          fi
        done

    - name: Test all modules
      run: |
        for dir in */; do
          if [ -f "$dir/go.mod" ]; then
            echo "Testing $dir"
            cd "$dir"
            go test -v .
            cd ..
          fi
        done
