# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build all modules
      run: |
        for dir in */; do
          if [ -f "$dir/go.mod" ]; then
            # Check if there are any .go files in this directory
            if find "$dir" -maxdepth 1 -name "*.go" | grep -q .; then
              echo "Building $dir"
              cd "$dir"
              go build -v .
              cd ..
            else
              echo "Skipping $dir (has go.mod but no Go files in root)"
            fi
          fi
        done

    - name: Test all modules
      run: |
        for dir in */; do
          if [ -f "$dir/go.mod" ]; then
            # Check if there are any .go files in this directory
            if find "$dir" -maxdepth 1 -name "*.go" | grep -q .; then
              echo "Testing $dir"
              cd "$dir"
              go test -v .
              cd ..
            else
              echo "Skipping $dir (has go.mod but no Go files in root)"
            fi
          fi
        done
